services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./исходные данные:/data

  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: analytics
    ports:
      - "8123:8123"
      - "9000:9000"

  spark:
    image: apache/spark:3.5.0
    command: tail -f /dev/null
    ports:
      - "8080:8080"
    volumes:
      - ./spark_jobs:/opt/spark/jobs
